// Package store is the brain's SQLite persistence — the desired-state source
// of truth (CONTROL_PLANE.md, APP_LIFECYCLE.md). Skeleton scope: the app
// instances table only. Users, sessions, audit, etc. land later.
package store

import (
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

// Instance is one installed app (a compose project, APP_LIFECYCLE.md).
type Instance struct {
	ID         string
	ManifestID string
	Name       string
	Slug       string
	Version    string
	State      string // installing | running | stopped | failed | uninstalling
	MDNSName   string
	CreatedAt  time.Time
}

// User is a malmo dashboard account. The brain mirrors a Linux account
// (USERS_AND_GROUPS.md); the *password* lives in PAM via host-agent, never
// in this row. `recovery_hash` is set only for admins (AUTH.md # Recovery).
type User struct {
	ID           string
	Username     string
	Role         string // "admin" | "member"
	RecoveryHash string // argon2id of recovery code; empty for non-admin
	CreatedAt    time.Time
}

const (
	RoleAdmin  = "admin"
	RoleMember = "member"
)

// Session is an issued dashboard session. Tokens are opaque random bytes,
// generated by the auth package and used as the cookie value (AUTH.md #
// Sessions). `last_seen_at` is updated on each authenticated request so the
// session can age out independently of issue time.
type Session struct {
	Token      string
	UserID     string
	CreatedAt  time.Time
	LastSeenAt time.Time
}

// ErrConflict signals a uniqueness collision (duplicate username, second
// admin during /v1/setup). The API maps it to 409.
var ErrConflict = errors.New("conflict")

// ErrNotFound covers any missing row — instance, user, or session. The API
// maps it to 404 (or 401 for sessions; the auth middleware translates).
var ErrNotFound = errors.New("not found")

type Store struct{ db *sql.DB }

func Open(path string) (*Store, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1) // sqlite: serialize writers, avoid "database is locked"
	if _, err := db.Exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;`); err != nil {
		return nil, err
	}
	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) migrate() error {
	_, err := s.db.Exec(`
		CREATE TABLE IF NOT EXISTS instances (
			id          TEXT PRIMARY KEY,
			manifest_id TEXT NOT NULL,
			name        TEXT NOT NULL,
			slug        TEXT NOT NULL UNIQUE,
			version     TEXT NOT NULL,
			state       TEXT NOT NULL,
			mdns_name   TEXT NOT NULL DEFAULT '',
			created_at  INTEGER NOT NULL
		);
		CREATE TABLE IF NOT EXISTS instance_images (
			instance_id TEXT NOT NULL,
			service     TEXT NOT NULL,
			image       TEXT NOT NULL,
			digest      TEXT NOT NULL,
			PRIMARY KEY (instance_id, service),
			FOREIGN KEY (instance_id) REFERENCES instances(id) ON DELETE CASCADE
		);
		CREATE TABLE IF NOT EXISTS users (
			id            TEXT PRIMARY KEY,
			username      TEXT NOT NULL UNIQUE,
			role          TEXT NOT NULL CHECK (role IN ('admin','member')),
			recovery_hash TEXT NOT NULL DEFAULT '',
			created_at    INTEGER NOT NULL
		);
		CREATE TABLE IF NOT EXISTS sessions (
			token        TEXT PRIMARY KEY,
			user_id      TEXT NOT NULL,
			created_at   INTEGER NOT NULL,
			last_seen_at INTEGER NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
		);`)
	return err
}

// InstanceImage is the resolved image pin for one service in one instance
// (APP_LIFECYCLE.md # image digest pinning).
type InstanceImage struct {
	Service string
	Image   string // original `image:tag` reference from the author's compose
	Digest  string // `sha256:…`
}

// SetInstanceImages replaces the pinned images for an instance in one
// transaction. Called once per install (and later, per update) after digests
// have been resolved.
func (s *Store) SetInstanceImages(instanceID string, images []InstanceImage) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`DELETE FROM instance_images WHERE instance_id=?`, instanceID); err != nil {
		return err
	}
	for _, img := range images {
		if _, err := tx.Exec(
			`INSERT INTO instance_images (instance_id, service, image, digest) VALUES (?,?,?,?)`,
			instanceID, img.Service, img.Image, img.Digest); err != nil {
			return err
		}
	}
	return tx.Commit()
}

// GetInstanceImages returns the pinned images for an instance, ordered by
// service name.
func (s *Store) GetInstanceImages(instanceID string) ([]InstanceImage, error) {
	rows, err := s.db.Query(
		`SELECT service, image, digest FROM instance_images
		 WHERE instance_id=? ORDER BY service`, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []InstanceImage
	for rows.Next() {
		var i InstanceImage
		if err := rows.Scan(&i.Service, &i.Image, &i.Digest); err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	return out, rows.Err()
}

func (s *Store) Create(i Instance) error {
	_, err := s.db.Exec(
		`INSERT INTO instances (id, manifest_id, name, slug, version, state, mdns_name, created_at)
		 VALUES (?,?,?,?,?,?,?,?)`,
		i.ID, i.ManifestID, i.Name, i.Slug, i.Version, i.State, i.MDNSName, i.CreatedAt.Unix())
	return err
}

func (s *Store) SetState(id, state string) error {
	res, err := s.db.Exec(`UPDATE instances SET state=? WHERE id=?`, state, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Store) SetMDNSName(id, name string) error {
	_, err := s.db.Exec(`UPDATE instances SET mdns_name=? WHERE id=?`, name, id)
	return err
}

func (s *Store) Delete(id string) error {
	_, err := s.db.Exec(`DELETE FROM instances WHERE id=?`, id)
	return err
}

func (s *Store) Get(id string) (Instance, error) {
	return scan(s.db.QueryRow(
		`SELECT id, manifest_id, name, slug, version, state, mdns_name, created_at
		 FROM instances WHERE id=?`, id))
}

func (s *Store) List() ([]Instance, error) {
	rows, err := s.db.Query(
		`SELECT id, manifest_id, name, slug, version, state, mdns_name, created_at
		 FROM instances ORDER BY created_at`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Instance
	for rows.Next() {
		i, err := scan(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, i)
	}
	return out, rows.Err()
}

// SlugTaken reports whether a slug is already used by an installed instance.
func (s *Store) SlugTaken(slug string) (bool, error) {
	var n int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM instances WHERE slug=?`, slug).Scan(&n)
	return n > 0, err
}

// CreateUser inserts a user row. Returns ErrConflict on duplicate username.
func (s *Store) CreateUser(u User) error {
	_, err := s.db.Exec(
		`INSERT INTO users (id, username, role, recovery_hash, created_at) VALUES (?,?,?,?,?)`,
		u.ID, u.Username, u.Role, u.RecoveryHash, u.CreatedAt.Unix())
	if err != nil && isUniqueErr(err) {
		return ErrConflict
	}
	return err
}

// CreateFirstAdmin inserts an admin user iff the users table is empty. Used
// by /v1/setup to atomically bootstrap the box and lose any race between two
// callers — the loser gets ErrConflict. Single transaction.
func (s *Store) CreateFirstAdmin(u User) error {
	if u.Role != RoleAdmin {
		return fmt.Errorf("CreateFirstAdmin: role must be admin, got %q", u.Role)
	}
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	var n int
	if err := tx.QueryRow(`SELECT COUNT(*) FROM users`).Scan(&n); err != nil {
		return err
	}
	if n > 0 {
		return ErrConflict
	}
	if _, err := tx.Exec(
		`INSERT INTO users (id, username, role, recovery_hash, created_at) VALUES (?,?,?,?,?)`,
		u.ID, u.Username, u.Role, u.RecoveryHash, u.CreatedAt.Unix()); err != nil {
		if isUniqueErr(err) {
			return ErrConflict
		}
		return err
	}
	return tx.Commit()
}

func (s *Store) GetUser(id string) (User, error) {
	return scanUser(s.db.QueryRow(
		`SELECT id, username, role, recovery_hash, created_at FROM users WHERE id=?`, id))
}

func (s *Store) GetUserByUsername(username string) (User, error) {
	return scanUser(s.db.QueryRow(
		`SELECT id, username, role, recovery_hash, created_at FROM users WHERE username=?`, username))
}

func (s *Store) ListUsers() ([]User, error) {
	rows, err := s.db.Query(
		`SELECT id, username, role, recovery_hash, created_at FROM users ORDER BY created_at`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []User
	for rows.Next() {
		u, err := scanUser(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, rows.Err()
}

func (s *Store) DeleteUser(id string) error {
	res, err := s.db.Exec(`DELETE FROM users WHERE id=?`, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// HasAnyUser is the bootstrap probe: /v1/auth/state uses it to route the UI
// between /setup and /login.
func (s *Store) HasAnyUser() (bool, error) {
	var n int
	err := s.db.QueryRow(`SELECT COUNT(*) FROM users`).Scan(&n)
	return n > 0, err
}

// CreateSession persists a freshly issued session. Caller picks the token.
func (s *Store) CreateSession(sess Session) error {
	_, err := s.db.Exec(
		`INSERT INTO sessions (token, user_id, created_at, last_seen_at) VALUES (?,?,?,?)`,
		sess.Token, sess.UserID, sess.CreatedAt.Unix(), sess.LastSeenAt.Unix())
	return err
}

// GetSession looks up a session by its token. ErrNotFound on miss; the auth
// middleware maps that to 401.
func (s *Store) GetSession(token string) (Session, error) {
	var sess Session
	var created, lastSeen int64
	err := s.db.QueryRow(
		`SELECT token, user_id, created_at, last_seen_at FROM sessions WHERE token=?`, token,
	).Scan(&sess.Token, &sess.UserID, &created, &lastSeen)
	if errors.Is(err, sql.ErrNoRows) {
		return Session{}, ErrNotFound
	}
	if err != nil {
		return Session{}, fmt.Errorf("scan session: %w", err)
	}
	sess.CreatedAt = time.Unix(created, 0)
	sess.LastSeenAt = time.Unix(lastSeen, 0)
	return sess, nil
}

// TouchSession updates last_seen_at — called by the auth middleware on every
// authenticated request.
func (s *Store) TouchSession(token string, at time.Time) error {
	_, err := s.db.Exec(`UPDATE sessions SET last_seen_at=? WHERE token=?`, at.Unix(), token)
	return err
}

// DeleteSession revokes a single session (logout).
func (s *Store) DeleteSession(token string) error {
	_, err := s.db.Exec(`DELETE FROM sessions WHERE token=?`, token)
	return err
}

// DeleteSessionsForUser revokes every session belonging to a user. Used after
// password reset and on user deletion (AUTH.md # Recovery).
func (s *Store) DeleteSessionsForUser(userID string) error {
	_, err := s.db.Exec(`DELETE FROM sessions WHERE user_id=?`, userID)
	return err
}

func scanUser(row scanner) (User, error) {
	var u User
	var created int64
	err := row.Scan(&u.ID, &u.Username, &u.Role, &u.RecoveryHash, &created)
	if errors.Is(err, sql.ErrNoRows) {
		return User{}, ErrNotFound
	}
	if err != nil {
		return User{}, fmt.Errorf("scan user: %w", err)
	}
	u.CreatedAt = time.Unix(created, 0)
	return u, nil
}

// isUniqueErr matches modernc.org/sqlite's UNIQUE-constraint error without
// importing the driver's error type. modernc returns errors whose string
// contains "UNIQUE constraint failed".
func isUniqueErr(err error) bool {
	return err != nil && strings.Contains(err.Error(), "UNIQUE constraint failed")
}

type scanner interface{ Scan(dest ...any) error }

func scan(row scanner) (Instance, error) {
	var i Instance
	var created int64
	err := row.Scan(&i.ID, &i.ManifestID, &i.Name, &i.Slug, &i.Version, &i.State, &i.MDNSName, &created)
	if errors.Is(err, sql.ErrNoRows) {
		return Instance{}, ErrNotFound
	}
	if err != nil {
		return Instance{}, fmt.Errorf("scan instance: %w", err)
	}
	i.CreatedAt = time.Unix(created, 0)
	return i, nil
}
